### ISSUE TITLE
Use EHLO instead of HELO

### ISSUE THREAD

**Issue by fgroeger** [Mikroservices/Smtp#11]
My mail provider only allows authenticating when using EHLO instead of HELO. What would you think how that should be implemented? I'd suggest a new configuration parameter where you can decide between EHLO and HELO (default).

I can implement, test and create a pull request if you'd like.

**Comment by mczachurski** [comment]
Hi, yes you can implement change and create PR. As you wrote the new configuration parameter will be the best solution (enum with .hello/.ehlo values). However, these commands cause that the server return different responses, thus probably it's not simple change of commands.

**Comment by fgroeger** [comment]
With my mail provider, i just needed to replace HELO with EHLO in your library and everything worked out of the box. I‘ll try some other mail providers I have access to.

**Comment by michaelkamphausen** [comment]
I had the smtp error "503 AUTH command used when not advertised" indicating the same problem.

I tried your changes @fgroeger and it works very well for me solving the error. Thank you!

**Comment by mczachurski** [comment]
Hi @fgroeger, are you working on PR? If not I can implement that change.

**Comment by fgroeger** [comment]
Hi @mczachurski, I have the changes ready locally and can push them later today after I get home from work.

**Comment by fgroeger** [comment]
Here you go:
https://github.com/Mikroservices/Smtp/pull/12
