### ISSUE TITLE
Emails with address only in BCC field.

### ISSUE THREAD

**Issue by omrd** [Mikroservices/Smtp#18]
Currently it doesn't seem possible to send emails with addresses only through the BCC field. Is there a way to allow this? An email should be able to send if any of the to, bcc, or cc fields have addresses.

**Comment by mczachurski** [comment]
Currently it's not possible. It's one of missing thing BCC and sending multiple emails at once.

**Comment by omrd** [comment]
Is there a plan to update?

**Comment by mczachurski** [comment]
I don’t know. Maybe after the summer I will have some time, but I can’t promise anything.

**Comment by mczachurski** [comment]
Implemented in version 3.0.0.
