### ISSUE TITLE
how to use app.clent to send

### ISSUE THREAD

**Issue by VineFiner** [Mikroservices/Smtp#8]
https://github.com/vapor-community/sendgrid

https://github.com/vapor-community/VaporMailgunService

They all have a shared client.

**Comment by mczachurski** [comment]
Hi. I've created new branch (feature/application-send) with new method in `Application` class. Now you can send email like that

```swift
app.smtp.send(email).map { result in
    ...
}
```

Please verify that change. If everything works for you then I will merge that change into the master branch.

**Comment by VineFiner** [comment]
> Hi. I've created new branch (feature/application-send) with new method in `Application` class. Now you can send email like that
> 
> 
> 
> ```swift
> 
> app.smtp.send(email).map { result in
> 
>     ...
> 
> }
> 
> ```
> 
> 
> 
> Please verify that change. If everything works for you then I will merge that change into the master branch.


Okay thank you.  I use this template project.  But I want to replace Mailgun.  
https://github.com/madsodgaard/vapor-auth-template/blob/master/Sources/App/Jobs/EmailJob.swift

**Comment by thuotdwz** [comment]
I am also looking for this function, can please include it in a new release? Thank you!

**Comment by mczachurski** [comment]
New version was released.

**Comment by VineFiner** [comment]
Sorry, no reply for a long time.  This can work.

There was an error during the test today.

req.smtp.send needs added  public。
